services:
  gamja:
    image: ghcr.io/ploos-as/gamja:latest
    container_name: gamja
    restart: unless-stopped
    environment:
      SOJU_HOST: ${SOJU_HOST:-soju}
      SOJU_PORT: ${SOJU_PORT:-8080}
      GAMJA_SERVER_URL: ${GAMJA_SERVER_URL:-/socket}
      GAMJA_AUTH: ${GAMJA_AUTH:-optional}
      GAMJA_AUTOJOIN: ${GAMJA_AUTOJOIN:-}
      GAMJA_NICK: ${GAMJA_NICK:-}
      GAMJA_AUTOCONNECT: ${GAMJA_AUTOCONNECT:-}
      GAMJA_PING: ${GAMJA_PING:-}
      GAMJA_OAUTH2_URL: ${GAMJA_OAUTH2_URL:-}
      GAMJA_OAUTH2_CLIENT_ID: ${GAMJA_OAUTH2_CLIENT_ID:-}
      GAMJA_OAUTH2_CLIENT_SECRET: ${GAMJA_OAUTH2_CLIENT_SECRET:-}
      GAMJA_OAUTH2_SCOPE: ${GAMJA_OAUTH2_SCOPE:-}
    ports:
      - "${GAMJA_PORT:-8080}:8080"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
